// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kasabi.demo.suppliersparts.domain;

import com.kasabi.demo.suppliersparts.domain.AddressIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AddressIntegrationTest_Roo_Configurable {
    
    declare @type: AddressIntegrationTest: @Configurable;
    
}
