// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kasabi.demo.suppliersparts.domain;

import com.kasabi.demo.suppliersparts.domain.CustomerOrder;
import com.kasabi.demo.suppliersparts.domain.CustomerOrderDataOnDemand;
import com.kasabi.demo.suppliersparts.domain.CustomerOrderIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CustomerOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CustomerOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CustomerOrderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CustomerOrderIntegrationTest: @Transactional;
    
    @Autowired
    private CustomerOrderDataOnDemand CustomerOrderIntegrationTest.dod;
    
    @Test
    public void CustomerOrderIntegrationTest.testCountCustomerOrders() {
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to initialize correctly", dod.getRandomCustomerOrder());
        long count = CustomerOrder.countCustomerOrders();
        Assert.assertTrue("Counter for 'CustomerOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CustomerOrderIntegrationTest.testFindCustomerOrder() {
        CustomerOrder obj = dod.getRandomCustomerOrder();
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to provide an identifier", id);
        obj = CustomerOrder.findCustomerOrder(id);
        Assert.assertNotNull("Find method for 'CustomerOrder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CustomerOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CustomerOrderIntegrationTest.testFindAllCustomerOrders() {
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to initialize correctly", dod.getRandomCustomerOrder());
        long count = CustomerOrder.countCustomerOrders();
        Assert.assertTrue("Too expensive to perform a find all test for 'CustomerOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CustomerOrder> result = CustomerOrder.findAllCustomerOrders();
        Assert.assertNotNull("Find all method for 'CustomerOrder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CustomerOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CustomerOrderIntegrationTest.testFindCustomerOrderEntries() {
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to initialize correctly", dod.getRandomCustomerOrder());
        long count = CustomerOrder.countCustomerOrders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CustomerOrder> result = CustomerOrder.findCustomerOrderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CustomerOrder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CustomerOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CustomerOrderIntegrationTest.testFlush() {
        CustomerOrder obj = dod.getRandomCustomerOrder();
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to provide an identifier", id);
        obj = CustomerOrder.findCustomerOrder(id);
        Assert.assertNotNull("Find method for 'CustomerOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCustomerOrder(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CustomerOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CustomerOrderIntegrationTest.testMergeUpdate() {
        CustomerOrder obj = dod.getRandomCustomerOrder();
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to provide an identifier", id);
        obj = CustomerOrder.findCustomerOrder(id);
        boolean modified =  dod.modifyCustomerOrder(obj);
        Integer currentVersion = obj.getVersion();
        CustomerOrder merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CustomerOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CustomerOrderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to initialize correctly", dod.getRandomCustomerOrder());
        CustomerOrder obj = dod.getNewTransientCustomerOrder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CustomerOrder' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'CustomerOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CustomerOrderIntegrationTest.testRemove() {
        CustomerOrder obj = dod.getRandomCustomerOrder();
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CustomerOrder' failed to provide an identifier", id);
        obj = CustomerOrder.findCustomerOrder(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CustomerOrder' with identifier '" + id + "'", CustomerOrder.findCustomerOrder(id));
    }
    
}
