// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kasabi.demo.suppliersparts.domain;

import com.kasabi.demo.suppliersparts.domain.Orderline;
import com.kasabi.demo.suppliersparts.domain.OrderlineDataOnDemand;
import com.kasabi.demo.suppliersparts.domain.OrderlineIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OrderlineIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OrderlineIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OrderlineIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OrderlineIntegrationTest: @Transactional;
    
    @Autowired
    private OrderlineDataOnDemand OrderlineIntegrationTest.dod;
    
    @Test
    public void OrderlineIntegrationTest.testCountOrderlines() {
        Assert.assertNotNull("Data on demand for 'Orderline' failed to initialize correctly", dod.getRandomOrderline());
        long count = Orderline.countOrderlines();
        Assert.assertTrue("Counter for 'Orderline' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OrderlineIntegrationTest.testFindOrderline() {
        Orderline obj = dod.getRandomOrderline();
        Assert.assertNotNull("Data on demand for 'Orderline' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Orderline' failed to provide an identifier", id);
        obj = Orderline.findOrderline(id);
        Assert.assertNotNull("Find method for 'Orderline' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Orderline' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OrderlineIntegrationTest.testFindAllOrderlines() {
        Assert.assertNotNull("Data on demand for 'Orderline' failed to initialize correctly", dod.getRandomOrderline());
        long count = Orderline.countOrderlines();
        Assert.assertTrue("Too expensive to perform a find all test for 'Orderline', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Orderline> result = Orderline.findAllOrderlines();
        Assert.assertNotNull("Find all method for 'Orderline' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Orderline' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OrderlineIntegrationTest.testFindOrderlineEntries() {
        Assert.assertNotNull("Data on demand for 'Orderline' failed to initialize correctly", dod.getRandomOrderline());
        long count = Orderline.countOrderlines();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Orderline> result = Orderline.findOrderlineEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Orderline' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Orderline' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OrderlineIntegrationTest.testFlush() {
        Orderline obj = dod.getRandomOrderline();
        Assert.assertNotNull("Data on demand for 'Orderline' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Orderline' failed to provide an identifier", id);
        obj = Orderline.findOrderline(id);
        Assert.assertNotNull("Find method for 'Orderline' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOrderline(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Orderline' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrderlineIntegrationTest.testMergeUpdate() {
        Orderline obj = dod.getRandomOrderline();
        Assert.assertNotNull("Data on demand for 'Orderline' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Orderline' failed to provide an identifier", id);
        obj = Orderline.findOrderline(id);
        boolean modified =  dod.modifyOrderline(obj);
        Integer currentVersion = obj.getVersion();
        Orderline merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Orderline' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrderlineIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Orderline' failed to initialize correctly", dod.getRandomOrderline());
        Orderline obj = dod.getNewTransientOrderline(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Orderline' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Orderline' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Orderline' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OrderlineIntegrationTest.testRemove() {
        Orderline obj = dod.getRandomOrderline();
        Assert.assertNotNull("Data on demand for 'Orderline' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Orderline' failed to provide an identifier", id);
        obj = Orderline.findOrderline(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Orderline' with identifier '" + id + "'", Orderline.findOrderline(id));
    }
    
}
