// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kasabi.demo.suppliersparts.domain;

import com.kasabi.demo.suppliersparts.domain.Part;
import com.kasabi.demo.suppliersparts.domain.PartDataOnDemand;
import com.kasabi.demo.suppliersparts.domain.PartIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PartIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PartIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PartIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PartIntegrationTest: @Transactional;
    
    @Autowired
    private PartDataOnDemand PartIntegrationTest.dod;
    
    @Test
    public void PartIntegrationTest.testCountParts() {
        Assert.assertNotNull("Data on demand for 'Part' failed to initialize correctly", dod.getRandomPart());
        long count = Part.countParts();
        Assert.assertTrue("Counter for 'Part' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PartIntegrationTest.testFindPart() {
        Part obj = dod.getRandomPart();
        Assert.assertNotNull("Data on demand for 'Part' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Part' failed to provide an identifier", id);
        obj = Part.findPart(id);
        Assert.assertNotNull("Find method for 'Part' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Part' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PartIntegrationTest.testFindAllParts() {
        Assert.assertNotNull("Data on demand for 'Part' failed to initialize correctly", dod.getRandomPart());
        long count = Part.countParts();
        Assert.assertTrue("Too expensive to perform a find all test for 'Part', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Part> result = Part.findAllParts();
        Assert.assertNotNull("Find all method for 'Part' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Part' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PartIntegrationTest.testFindPartEntries() {
        Assert.assertNotNull("Data on demand for 'Part' failed to initialize correctly", dod.getRandomPart());
        long count = Part.countParts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Part> result = Part.findPartEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Part' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Part' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PartIntegrationTest.testFlush() {
        Part obj = dod.getRandomPart();
        Assert.assertNotNull("Data on demand for 'Part' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Part' failed to provide an identifier", id);
        obj = Part.findPart(id);
        Assert.assertNotNull("Find method for 'Part' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPart(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Part' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PartIntegrationTest.testMergeUpdate() {
        Part obj = dod.getRandomPart();
        Assert.assertNotNull("Data on demand for 'Part' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Part' failed to provide an identifier", id);
        obj = Part.findPart(id);
        boolean modified =  dod.modifyPart(obj);
        Integer currentVersion = obj.getVersion();
        Part merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Part' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PartIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Part' failed to initialize correctly", dod.getRandomPart());
        Part obj = dod.getNewTransientPart(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Part' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Part' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Part' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PartIntegrationTest.testRemove() {
        Part obj = dod.getRandomPart();
        Assert.assertNotNull("Data on demand for 'Part' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Part' failed to provide an identifier", id);
        obj = Part.findPart(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Part' with identifier '" + id + "'", Part.findPart(id));
    }
    
}
