// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kasabi.demo.suppliersparts.domain;

import com.kasabi.demo.suppliersparts.domain.Supplier;
import com.kasabi.demo.suppliersparts.domain.SupplierDataOnDemand;
import com.kasabi.demo.suppliersparts.domain.SupplierIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SupplierIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SupplierIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SupplierIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SupplierIntegrationTest: @Transactional;
    
    @Autowired
    private SupplierDataOnDemand SupplierIntegrationTest.dod;
    
    @Test
    public void SupplierIntegrationTest.testCountSuppliers() {
        Assert.assertNotNull("Data on demand for 'Supplier' failed to initialize correctly", dod.getRandomSupplier());
        long count = Supplier.countSuppliers();
        Assert.assertTrue("Counter for 'Supplier' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SupplierIntegrationTest.testFindSupplier() {
        Supplier obj = dod.getRandomSupplier();
        Assert.assertNotNull("Data on demand for 'Supplier' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Supplier' failed to provide an identifier", id);
        obj = Supplier.findSupplier(id);
        Assert.assertNotNull("Find method for 'Supplier' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Supplier' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SupplierIntegrationTest.testFindAllSuppliers() {
        Assert.assertNotNull("Data on demand for 'Supplier' failed to initialize correctly", dod.getRandomSupplier());
        long count = Supplier.countSuppliers();
        Assert.assertTrue("Too expensive to perform a find all test for 'Supplier', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Supplier> result = Supplier.findAllSuppliers();
        Assert.assertNotNull("Find all method for 'Supplier' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Supplier' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SupplierIntegrationTest.testFindSupplierEntries() {
        Assert.assertNotNull("Data on demand for 'Supplier' failed to initialize correctly", dod.getRandomSupplier());
        long count = Supplier.countSuppliers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Supplier> result = Supplier.findSupplierEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Supplier' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Supplier' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SupplierIntegrationTest.testFlush() {
        Supplier obj = dod.getRandomSupplier();
        Assert.assertNotNull("Data on demand for 'Supplier' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Supplier' failed to provide an identifier", id);
        obj = Supplier.findSupplier(id);
        Assert.assertNotNull("Find method for 'Supplier' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySupplier(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Supplier' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SupplierIntegrationTest.testMergeUpdate() {
        Supplier obj = dod.getRandomSupplier();
        Assert.assertNotNull("Data on demand for 'Supplier' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Supplier' failed to provide an identifier", id);
        obj = Supplier.findSupplier(id);
        boolean modified =  dod.modifySupplier(obj);
        Integer currentVersion = obj.getVersion();
        Supplier merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Supplier' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SupplierIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Supplier' failed to initialize correctly", dod.getRandomSupplier());
        Supplier obj = dod.getNewTransientSupplier(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Supplier' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Supplier' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Supplier' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SupplierIntegrationTest.testRemove() {
        Supplier obj = dod.getRandomSupplier();
        Assert.assertNotNull("Data on demand for 'Supplier' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Supplier' failed to provide an identifier", id);
        obj = Supplier.findSupplier(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Supplier' with identifier '" + id + "'", Supplier.findSupplier(id));
    }
    
}
