// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kasabi.demo.suppliersparts.domain;

import com.kasabi.demo.suppliersparts.domain.Part;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Part_Roo_Configurable {
    
    declare @type: Part: @Configurable;
    
}
