// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.kasabi.demo.suppliersparts.domain;

import com.kasabi.demo.suppliersparts.domain.Supplier;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Supplier_Roo_Configurable {
    
    declare @type: Supplier: @Configurable;
    
}
